apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-internet-urls
  labels:
    app: monitor-internet-urls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor-internet-urls
  template:
    metadata:
      labels:
        app: monitor-internet-urls
    spec:
      containers:
        - name: monitor-internet-urls
          image: akshaygirpunje/pythonmonitorurls:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: LISTENING_PORT
              value: "8001"
      imagePullSecrets:
      - name: akshaygirpunje-dockerrepo

