apiVersion: v1
kind: Service
metadata:
  name: monitor-internet-urls
  labels:
    app: monitor-internet-urls
spec:
  type: NodePort
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
      name: http
  selector:
    app: monitor-internet-urls
